export default [
  // API
  'LOGIN',

  // Roles request server
  'FETCH_ROLES',
  'FETCH_STATUS_ROLE_CURRENT',
  'UPDATE_ROLE',

  // Roles in redux
  'CHANGE_DATA_ROLE',

  // Project
  'FETCH_PROJECTS',
  'SEARCH_PROJECTS',
  'CREATE_PROJECT',
  'FETCH_PROJECTS_DETAIL',
  'UPDATE_PROJECT',
  'DELETE_PROJECT',
  'CHANGE_STATUS_PROJECT',

  // Employee
  'FETCH_EMPLOYEES',
  'SEARCH_EMPLOYEES',
  'FETCH_PROJECTS_BY_EMPLOYEE_ID',
  'DELETE_EMPLOYEE_FROM_PROJECT',
  'UPDATE_EMPLOYEE',
  'FETCH_ROLES',
  'IMPORT_EMPLOYEES',
  'CREATE_EMPLOYEE',

  // Report
  'FETCH_REPORTS',
  'SEARCH_REPORTS',

  // Store
  'CLEAR_STORE',
  'SET_PERMISSIONS'
]
